# Generated by Django 4.2.2 on 2023-07-27 04:47

import beekeeper_web_api.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(default='admin', upload_to='images/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('count_purchase', models.IntegerField(default=0, verbose_name='кол-во покупок')),
                ('category', models.ManyToManyField(blank=True, related_name='category_list', to='beekeeper_web_api.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Type_weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес в граммах')),
            ],
            options={
                'verbose_name': 'Тип веса товара',
                'verbose_name_plural': 'Типы веса товара',
            },
        ),
        migrations.CreateModel(
            name='RatingProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, 'Awesome'), (4, 'Good'), (3, 'Satisfactorily'), (2, 'Bad'), (1, 'Very Bad')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_product', to='beekeeper_web_api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объект рейтинга продукта',
                'verbose_name_plural': 'Объекты рейтинга продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='RUB', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=14, verbose_name='Цена варианта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productItemList', to='beekeeper_web_api.product')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beekeeper_web_api.type_weight')),
            ],
            options={
                'verbose_name': 'Вариант продукта',
                'verbose_name_plural': 'Варианты продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='list_weight',
            field=models.ManyToManyField(null=True, related_name='list_weight', to='beekeeper_web_api.type_weight'),
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=beekeeper_web_api.models.ImageProduct.get_galery_item_url)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageProductList', to='beekeeper_web_api.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение продукта',
                'verbose_name_plural': 'Дополнительные изображения продуктов',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productItem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beekeeper_web_api.productitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объект избранного',
                'verbose_name_plural': 'Объекты избранного',
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('productItem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beekeeper_web_api.productitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объект корзины',
                'verbose_name_plural': 'Объекты корзины',
            },
        ),
    ]
