# Generated by Django 4.2.2 on 2023-07-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='list_weight',
        ),
    ]
