# Generated by Django 4.2.2 on 2023-07-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0002_remove_product_list_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('height', models.FloatField(verbose_name='Высота')),
            ],
        ),
        migrations.AddField(
            model_name='productitem',
            name='dimensions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beekeeper_web_api.dimensionsproduct', verbose_name='Габариты'),
        ),
    ]
