# Generated by Django 4.2.2 on 2023-07-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('beekeeper_web_api', '0002_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_transaction', to='delivery.deliverytransaction'),
        ),
    ]
