# Generated by Django 4.2.2 on 2023-07-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0003_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_index',
        ),
    ]
