# Generated by Django 4.2.2 on 2023-08-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0004_alter_dimensionsproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='weight',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='beekeeper_web_api.type_weight'),
        ),
    ]
