# Generated by Django 4.2.2 on 2023-07-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0004_remove_order_order_address_remove_order_order_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type_packaging',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='type_packaging',
        ),
        migrations.DeleteModel(
            name='Type_packaging',
        ),
    ]
