# Generated by Django 4.2.2 on 2023-07-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0005_remove_product_type_packaging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Одобрен', 'Approved'), ('Не одобренный', 'Not Approved')], default='Не одобренный'),
        ),
    ]
