# Generated by Django 4.2.2 on 2023-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Одобрен', 'Approved'), ('Не одобренный', 'Not Approved'), ('Закрытый', 'Closed')], default='Не одобренный'),
        ),
    ]
