# Generated by Django 4.2.2 on 2023-08-25 16:02

import beekeeper_web_api.models
import beekeeper_web_api.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0007_dimensionsproduct_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='photo',
            field=models.ImageField(upload_to=beekeeper_web_api.models.ImageProduct.get_galery_item_url, validators=[beekeeper_web_api.validate.image_ot_quotation_mark]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, validators=[beekeeper_web_api.validate.not_quotation_mark], verbose_name='Название продукта'),
        ),
    ]
