# Generated by Django 4.2.2 on 2023-09-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0008_alter_imageproduct_photo_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='productItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basket_item_list', to='beekeeper_web_api.productitem'),
        ),
    ]
