# Generated by Django 4.2.2 on 2023-09-20 16:08

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0009_alter_basketitem_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='old_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=14, verbose_name='Не указывать'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='old_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='RUB', editable=False, max_length=3),
        ),
    ]
