# Generated by Django 4.2.2 on 2023-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0010_productitem_is_sale_productitem_old_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInfoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Главный блок', 'Main Block'), ('Преимущества', 'Preimusestva'), ('Эко золото', 'Eco Zoloto'), ('Нижный блок', 'Niz Block'), ('Контактная информация', 'Contact Data')], null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Блок сайта',
                'verbose_name_plural': 'Блоки сайта',
            },
        ),
    ]
