# Generated by Django 4.2.2 on 2023-12-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0012_additem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockinfosite',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Главный блок'), ('2', 'Преимущества блок'), ('3', 'Эко блок'), ('4', 'Нижний блок'), ('5', 'Контактная информация блок')], null=True),
        ),
    ]
