# Generated by Django 4.2.2 on 2023-12-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0013_alter_blockinfosite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_item_list', to='beekeeper_web_api.blockinfosite'),
        ),
    ]
