# Generated by Django 4.2.2 on 2023-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0014_alter_additem_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockinfosite',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
