# Generated by Django 4.2.2 on 2024-01-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeper_web_api', '0016_blockinfosite_email_blockinfosite_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
