# Generated by Django 4.2.2 on 2023-09-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_notify_time'),
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notify.notify')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='notify_list',
            field=models.ManyToManyField(related_name='order', through='orders.OrderNotify', to='notify.notify'),
        ),
    ]
