# Generated by Django 4.2.2 on 2023-09-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordernotify_order_notify_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notify_list',
        ),
        migrations.DeleteModel(
            name='OrderNotify',
        ),
    ]
