# Generated by Django 4.2.2 on 2023-11-28 14:38

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_notify_list_delete_ordernotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[user.validators.number_validator], verbose_name='Номер телефона заказчика'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_order',
            field=models.CharField(choices=[('Заказ через службу доставки', 'Delivery'), ('Заказ через собственную доставку', 'Delivery Me'), ('Самовывоз', 'Pickup Delivery')], default='Заказ через службу доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_payment',
            field=models.CharField(choices=[('Онлайн оплата', 'Online'), ('Личная оплата', 'Offline')], default='Онлайн оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=3, default=Decimal('0'), default_currency='RUB', max_digits=10, verbose_name='Сумма транзакции'),
        ),
    ]
