# Generated by Django 4.2.2 on 2023-11-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_number_order_type_order_order_type_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_payment',
        ),
    ]
