# Generated by Django 4.2.2 on 2023-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_sending',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
