# Generated by Django 4.2.2 on 2023-08-09 05:13

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_mainuser_is_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[user.validators.number_validator], verbose_name='Номер пользователя'),
        ),
    ]
