# Generated by Django 4.2.2 on 2023-08-09 05:17

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_mainuser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[user.validators.number_validator], verbose_name='Номер пользователя'),
        ),
    ]
