# Generated by Django 4.2.2 on 2023-09-18 15:46

from django.db import migrations, models
import user.validate


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_mainuser_is_email_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='password',
            field=models.CharField(max_length=128, validators=[user.validate.user_password_validate], verbose_name='password'),
        ),
    ]
