# Generated by Django 4.2.2 on 2023-07-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('track_number', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('На проверке', 'Under Review'), ('Ожидание доставки', 'Waiting For Dispatch'), ('Отправлен', 'Sent'), ('Ожидает в пункте выдачи', 'Waiting At The Pickup Point'), ('Принят', 'Accepted'), ('Отменен', 'Closed')], default='На проверке')),
                ('delivery_method', models.CharField(choices=[('Курьер', 'Courier'), ('До пункта выдачи', 'To Pickup Point')], default='До пункта выдачи')),
                ('where', models.CharField(default='Уварово ПМЗ UVA01', max_length=200)),
            ],
            options={
                'verbose_name': 'Транзакция доставки',
                'verbose_name_plural': 'Транзакции доставок',
            },
        ),
    ]
