# Generated by Django 4.2.2 on 2023-07-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverytransaction',
            old_name='number',
            new_name='uuid',
        ),
    ]
