# Generated by Django 4.2.2 on 2023-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytransaction',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена доставки'),
        ),
    ]
