# Generated by Django 4.2.2 on 2023-08-09 05:23

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliverytransaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytransaction',
            name='number',
            field=models.CharField(default='', max_length=11, validators=[user.validators.number_validator], verbose_name='Номер телефона заказчика'),
        ),
    ]
