# Generated by Django 4.2.2 on 2023-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_number_deliverytransaction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytransaction',
            name='uuid',
            field=models.CharField(max_length=100),
        ),
    ]
