# Generated by Django 4.2.2 on 2023-08-10 14:33

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverytransaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytransaction',
            name='number',
            field=models.CharField(max_length=11, validators=[user.validators.number_validator], verbose_name='Номер телефона заказчика'),
        ),
        migrations.AlterField(
            model_name='deliverytransaction',
            name='track_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='deliverytransaction',
            name='uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
