# Generated by Django 4.2.2 on 2023-07-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliverytransaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytransaction',
            name='status',
            field=models.CharField(choices=[('На проверке', 'Under Review'), ('Ожидание доставки', 'Waiting For Dispatch'), ('Отправлен', 'Sent'), ('Ожидает в пункте выдачи', 'Waiting At The Pickup Point'), ('Принят', 'Accepted')], default='На проверке'),
        ),
        migrations.AddField(
            model_name='deliverytransaction',
            name='track_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
