# Generated by Django 4.2.2 on 2023-07-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverytransaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytransaction',
            name='delivery_method',
            field=models.CharField(choices=[('Курьер', 'Courier'), ('До пункта выдачи', 'To Pickup Point')], default='До пункта выдачи'),
        ),
    ]
