# Generated by Django 4.2.2 on 2023-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_deliverytransaction_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
            ],
        ),
    ]
