# Generated by Django 4.2.2 on 2023-07-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliverytransaction_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytransaction',
            name='where',
            field=models.CharField(default='Уварово ПМЗ UVA01', max_length=200),
        ),
    ]
