# Generated by Django 4.2.2 on 2023-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliverystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytransaction',
            name='delivery_type',
            field=models.CharField(choices=[('Заказ через службу доставки', 'Delivery'), ('Заказ через собственную доставку', 'Delivery Me'), ('Самовывоз', 'Pickup Delivery')], default='Заказ через службу доставки'),
        ),
    ]
