# Generated by Django 4.2.2 on 2023-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliverytransaction_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytransaction',
            name='status',
            field=models.CharField(choices=[('На проверке', 'Under Review'), ('Ожидание доставки', 'Waiting For Dispatch'), ('Отправлен', 'Sent'), ('Ожидает в пункте выдачи', 'Waiting At The Pickup Point'), ('Принят', 'Accepted'), ('Отменен', 'Closed')], default='На проверке'),
        ),
    ]
