# Generated by Django 4.2.2 on 2023-08-04 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название рассылки')),
                ('message', models.CharField(choices=[('О новых продуктах / product', 'Product'), ('О новостях / news', 'News')], default='О новых продуктах / product')),
                ('data', models.DateTimeField(null=True, verbose_name='Время начала рассылки')),
                ('periods', models.BooleanField(default=False, verbose_name='Повторять задачу?')),
                ('task_id', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_sending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
