# Generated by Django 4.2.2 on 2023-08-01 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название рассылки')),
                ('message', models.CharField(choices=[('О новых продуктах', 'Product'), ('О скидках', 'Sale'), ('О новостях', 'News')], default='О новых продуктах')),
                ('data', models.DateTimeField(null=True, verbose_name='Время начала рассылки')),
                ('periods', models.BooleanField(default=False, verbose_name='Повторять задачу?')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
                ('user_list', models.ManyToManyField(related_name='specific_sending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
