# Generated by Django 4.2.2 on 2023-08-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificsending',
            name='task_id',
            field=models.TextField(default=''),
        ),
    ]
