# Generated by Django 4.2.2 on 2023-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0002_alter_specificsending_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificsending',
            name='user_list',
        ),
        migrations.AlterField(
            model_name='specificsending',
            name='message',
            field=models.CharField(choices=[('О новых продуктах / product', 'Product'), ('О скидках / sale', 'Sale'), ('О новостях / news', 'News')], default='О новых продуктах / product'),
        ),
    ]
