# Generated by Django 4.2.2 on 2023-07-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('main_image', models.ImageField(default='news/default.png', upload_to='')),
                ('main_text', models.TextField(blank=True)),
                ('context', models.TextField(blank=True, verbose_name='Разметка новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
