# Generated by Django 4.2.2 on 2023-06-17 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес в граммах')),
            ],
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='favorite_product',
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productItemList', to='online_store.product')),
                ('type_packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store.type_packaging')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store.type_weight')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productItem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_store.productitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('productItem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_store.productitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='list_weight',
            field=models.ManyToManyField(null=True, related_name='list_weight', to='online_store.type_weight'),
        ),
    ]
