# Generated by Django 4.2.1 on 2023-05-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='image',
            field=models.ImageField(default='admin', upload_to='images/%Y/%m/%d/', verbose_name='Изображение пользователя'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='admin', upload_to='images/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
