# Generated by Django 4.2.1 on 2023-05-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_mainuser_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_purchase',
            field=models.IntegerField(default=0, verbose_name='кол-во покупок'),
        ),
    ]
