# Generated by Django 4.2.2 on 2023-07-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_alter_mainuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='email',
        ),
    ]
