# Generated by Django 4.2.2 on 2023-06-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_type_weight_remove_mainuser_basket_basketitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='online_store.type_weight'),
        ),
    ]
