# Generated by Django 4.2.2 on 2023-06-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_type_weight_remove_mainuser_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='basket',
            field=models.ManyToManyField(related_name='basket', through='online_store.BasketItem', to='online_store.productitem'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='favorite_product',
            field=models.ManyToManyField(related_name='favorite_product', through='online_store.FavoriteItem', to='online_store.productitem'),
        ),
    ]
