# Generated by Django 4.2.2 on 2023-06-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tovar_list',
            field=models.ManyToManyField(related_name='product_list_transaction', to='online_store.orderitem', verbose_name='Товары заказа'),
        ),
    ]
