# Generated by Django 4.2.2 on 2023-06-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_alter_basketitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='basket',
            field=models.ManyToManyField(related_name='basket', through='online_store.BasketItem', to='online_store.product'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store.type_weight'),
        ),
    ]
