# Generated by Django 4.2.2 on 2023-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_remove_mainuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='email',
            field=models.EmailField(default='asd@asd.ru', max_length=254),
        ),
    ]
