# Generated by Django 4.2.2 on 2023-06-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_alter_order_tovar_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tovar_list',
        ),
    ]
