# Generated by Django 4.2.2 on 2023-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_mainuser_basket_alter_basketitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
