# Generated by Django 4.2.2 on 2023-06-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_remove_order_tovar_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Order',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='product_list_transaction', to='online_store.order'),
        ),
    ]
