# Generated by Django 4.2.2 on 2023-06-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0006_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
    ]
