# Generated by Django 4.2.1 on 2023-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0006_alter_mainuser_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='login',
            field=models.CharField(max_length=50, unique=True, verbose_name='логин'),
        ),
    ]
