# Generated by Django 4.2.2 on 2023-06-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0007_rename_order_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='productItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store.productitem'),
        ),
    ]
