# Generated by Django 4.2.1 on 2023-05-27 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0007_alter_mainuser_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Сумма баланса'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='image',
            field=models.ImageField(blank=True, default='images/ds.png', upload_to='images/%Y/%m/%d/', verbose_name='Изображение пользователя'),
        ),
        migrations.CreateModel(
            name='UserBalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Сумма транзакции')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
