# Generated by Django 4.2.1 on 2023-05-27 15:15

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0008_mainuser_balance_alter_mainuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=6, default=Decimal('0'), default_currency='RUB', max_digits=18, verbose_name='Сумма баланса'),
        ),
    ]
