# Generated by Django 4.2.1 on 2023-05-27 15:17

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0009_mainuser_balance_currency_alter_mainuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=14, verbose_name='Сумма баланса'),
        ),
        migrations.AlterField(
            model_name='userbalancechange',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма транзакции'),
        ),
    ]
