# Generated by Django 4.2.1 on 2023-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0010_alter_mainuser_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalancechange',
            name='tovar_list',
            field=models.ManyToManyField(related_name='product_list_transaction', to='online_store.product', verbose_name='Товары заказа'),
        ),
    ]
