# Generated by Django 4.2.1 on 2023-05-27 15:35

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0012_mainuser_groups_mainuser_is_active_mainuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='mainuser',
            old_name='login',
            new_name='username',
        ),
    ]
