# Generated by Django 4.2.1 on 2023-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0013_alter_mainuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
