# Generated by Django 4.2.1 on 2023-05-27 15:40

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0014_mainuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalancechange',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='userbalancechange',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=14, verbose_name='Сумма транзакции'),
        ),
    ]
