# Generated by Django 4.2.1 on 2023-05-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0018_alter_mainuser_managers_mainuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='username',
            field=models.CharField(default='1', max_length=50, unique=True, verbose_name='логин'),
        ),
    ]
