# Generated by Django 4.2.1 on 2023-05-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0019_mainuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='username',
            field=models.CharField(default='1', max_length=50, verbose_name='логин'),
        ),
    ]
