# Generated by Django 4.2.1 on 2023-05-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0021_alter_mainuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='логин'),
        ),
    ]
