# Generated by Django 4.2.1 on 2023-05-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0022_alter_mainuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='favorite_product',
            field=models.ManyToManyField(related_name='favorite_product', to='online_store.product'),
        ),
    ]
