# Generated by Django 4.2.1 on 2023-06-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0023_mainuser_favorite_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='login',
        ),
    ]
