# Generated by Django 4.2.1 on 2023-06-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0024_remove_mainuser_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Type_packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа упаковки')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_list', to='online_store.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_packaging',
            field=models.ManyToManyField(blank=True, null=True, related_name='type_packaging_list', to='online_store.type_packaging'),
        ),
    ]
