# Generated by Django 4.2.1 on 2023-06-07 10:44

from django.db import migrations, models
import django.db.models.deletion
import online_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0025_category_type_packaging_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=online_store.models.get_galery_item_url)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_list', to='online_store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_packaging',
            field=models.ManyToManyField(blank=True, related_name='type_packaging_list', to='online_store.type_packaging'),
        ),
        migrations.CreateModel(
            name='ImageProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageProduct', to='online_store.imageproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='online_store.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='galery',
            field=models.ManyToManyField(blank=True, related_name='galery', through='online_store.ImageProductList', to='online_store.imageproduct'),
        ),
    ]
