# Generated by Django 4.2.1 on 2023-06-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0026_imageproduct_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproductlist',
            name='ImageProduct',
        ),
        migrations.RemoveField(
            model_name='imageproductlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='galery',
        ),
        migrations.DeleteModel(
            name='ImageProduct',
        ),
        migrations.DeleteModel(
            name='ImageProductList',
        ),
    ]
