# Generated by Django 4.2.1 on 2023-06-07 10:49

from django.db import migrations, models
import django.db.models.deletion
import online_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0027_remove_imageproductlist_imageproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=online_store.models.get_galery_item_url)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='online_store.product')),
            ],
        ),
    ]
