# Generated by Django 4.2.1 on 2023-06-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0028_imageproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageProductList', to='online_store.product', verbose_name='Продукт'),
        ),
    ]
