# Generated by Django 4.2.2 on 2023-09-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertelegram',
            name='is_sending_code',
            field=models.BooleanField(default=False),
        ),
    ]
