# Generated by Django 4.2.2 on 2023-08-29 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Новости', 'News'), ('Продукты', 'Product'), ('Заказы', 'Order')])),
                ('text', models.CharField(max_length=120)),
                ('is_viewed', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(related_name='notify_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
