# Generated by Django 4.2.2 on 2023-08-30 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0002_notify_all_remove_notify_users_notify_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
