# Generated by Django 4.2.2 on 2023-08-31 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0003_alter_notify_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='is_viewed',
        ),
        migrations.AddField(
            model_name='notify',
            name='is_viewed',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_viewed_notify', to=settings.AUTH_USER_MODEL),
        ),
    ]
