# Generated by Django 4.2.2 on 2023-09-02 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0004_remove_notify_is_viewed_notify_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='is_viewed',
            field=models.ManyToManyField(blank=True, related_name='is_viewed_notify', to=settings.AUTH_USER_MODEL),
        ),
    ]
