# Generated by Django 4.2.2 on 2023-09-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_alter_notify_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
