# Generated by Django 4.2.2 on 2023-09-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_deliverytransaction_number_and_more'),
        ('notify', '0006_notify_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_list', to='delivery.deliverytransaction'),
        ),
    ]
