# Generated by Django 4.2.2 on 2023-09-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_notify_list_delete_ordernotify'),
        ('delivery', '0004_alter_deliverytransaction_number_and_more'),
        ('notify', '0007_notify_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_list', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_list', to='delivery.deliverytransaction'),
        ),
    ]
