# Generated by Django 4.2.2 on 2023-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='url',
            field=models.TextField(default='https://yoomoney.ru/checkout/payments/v2/success?orderId=2c50b057-000f-5000-a000-125621fffc5c'),
        ),
    ]
