version: '3.9'

services:
  database:    
    image: postgres:latest
    environment:
    - POSTGRES_DB=beekeeper
    - POSTGRES_USER=gagtain
    - POSTGRES_PASSWORD=13576422
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gagtain -d beekeeper"]
      interval: 10s
      timeout: 5s
      retries: 80
      start_period: 10s
    networks: 
      - forwebapi

  webapi_one:
    build: 
      context: ../backend/
    container_name: webapi_one
    environment:
      - DJANGO_SUPERUSER_PASSWORD=13
      - DEBUG=False
      - DATABASE_HOST=database
    command: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python3 manage.py createsuperuser --noinput --username gag && python manage.py runserver 0.0.0.0:8000"]
    
    
    ports:
        - 8000:8000
    networks: 
      - forwebapi
    depends_on:
        database:
          condition: service_healthy


networks:
  forwebapi:
    name: forwebapi
    driver: bridge